/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.almacen.view.principal;

import com.almacen.model.principal.PrincipalModel;
import java.awt.Color;
import java.awt.IllegalComponentStateException;
import javax.swing.JOptionPane;

/**
 *
 * @author djoso
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form principalView
     */
    public PrincipalView() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogModificacione = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSalidaMaterial = new javax.swing.JLabel();
        lblEntradaMaterial = new javax.swing.JLabel();
        lblHistorial = new javax.swing.JLabel();
        lblNuevoMaterial = new javax.swing.JLabel();
        lblModificacion = new javax.swing.JLabel();
        lblNuevoUsuario = new javax.swing.JLabel();
        panelBusqueda = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btbCerrarSesion = new javax.swing.JButton();

        dialogModificacione.setFocusTraversalPolicyProvider(true);

        jLabel4.setText("Que deseas modificar ?");

        jLabel5.setText("Usuario");

        jLabel6.setText("Material");

        jLabel7.setText("Categoria");

        jLabel8.setText("Tipo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogModificacioneLayout = new javax.swing.GroupLayout(dialogModificacione.getContentPane());
        dialogModificacione.getContentPane().setLayout(dialogModificacioneLayout);
        dialogModificacioneLayout.setHorizontalGroup(
            dialogModificacioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogModificacioneLayout.setVerticalGroup(
            dialogModificacioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("principalView"); // NOI18N

        jLabel2.setText("Acciones");

        jLabel3.setText("Almacen ...");

        lblSalidaMaterial.setText("Salida Material");
        lblSalidaMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalidaMaterialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalidaMaterialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalidaMaterialMouseExited(evt);
            }
        });

        lblEntradaMaterial.setText("Entrada Material");
        lblEntradaMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEntradaMaterialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEntradaMaterialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEntradaMaterialMouseExited(evt);
            }
        });

        lblHistorial.setText("Historial");
        lblHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHistorialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHistorialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHistorialMouseExited(evt);
            }
        });

        lblNuevoMaterial.setText("Material Nuevo");
        lblNuevoMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNuevoMaterialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNuevoMaterialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNuevoMaterialMouseExited(evt);
            }
        });

        lblModificacion.setText("Modificacion");
        lblModificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModificacionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModificacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModificacionMouseExited(evt);
            }
        });

        lblNuevoUsuario.setText("Añadir nuevo usuario");
        lblNuevoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNuevoUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNuevoUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNuevoUsuarioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSalidaMaterial)
                            .addComponent(lblNuevoMaterial)
                            .addComponent(lblEntradaMaterial)
                            .addComponent(lblModificacion)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNuevoUsuario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHistorial)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(112, 112, 112)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalidaMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEntradaMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblModificacion)
                .addGap(11, 11, 11)
                .addComponent(lblNuevoMaterial)
                .addGap(34, 34, 34)
                .addComponent(lblHistorial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(lblNuevoUsuario)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jLabel1.setText("Busqueda Rapida");

        btnBuscar.setText("Buscar");

        jTextArea1.setBackground(new java.awt.Color(0, 153, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Busqueda aparecera aqui");
        jTextArea1.setEnabled(false);
        jTextArea1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout panelBusquedaLayout = new javax.swing.GroupLayout(panelBusqueda);
        panelBusqueda.setLayout(panelBusquedaLayout);
        panelBusquedaLayout.setHorizontalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelBusquedaLayout.setVerticalGroup(
            panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jSplitPane1.setRightComponent(panelBusqueda);

        btbCerrarSesion.setText("Cerrar Sesion");
        btbCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(413, Short.MAX_VALUE)
                .addComponent(btbCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(454, Short.MAX_VALUE)
                .addComponent(btbCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    PrincipalModel principal = new PrincipalModel();

    private void btbCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCerrarSesionActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Desea cerrar sesion") == 0) {
            if (principal.cerrarSesion()) {
                this.dispose();
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btbCerrarSesionActionPerformed

    private void lblSalidaMaterialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalidaMaterialMouseEntered
        lblSalidaMaterial.setForeground(Color.red);
        lblSalidaMaterial.setToolTipText("Se puede realizar retiros de material");
    }//GEN-LAST:event_lblSalidaMaterialMouseEntered

    private void lblSalidaMaterialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalidaMaterialMouseExited
        lblSalidaMaterial.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblSalidaMaterialMouseExited

    private void lblSalidaMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalidaMaterialMouseClicked
        if (principal.ejecutarSalidaMat()) {
            this.dispose();
        }
    }//GEN-LAST:event_lblSalidaMaterialMouseClicked

    private void lblEntradaMaterialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntradaMaterialMouseEntered
        lblEntradaMaterial.setForeground(Color.red);
        lblEntradaMaterial.setToolTipText("Ingresar materiales al almacen");
    }//GEN-LAST:event_lblEntradaMaterialMouseEntered

    private void lblEntradaMaterialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntradaMaterialMouseExited
        lblEntradaMaterial.setForeground(Color.black);
    }//GEN-LAST:event_lblEntradaMaterialMouseExited

    private void lblEntradaMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntradaMaterialMouseClicked
        if (principal.ejecutarEntradaMat()) {
            this.dispose();
        }
    }//GEN-LAST:event_lblEntradaMaterialMouseClicked

    private void lblHistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistorialMouseClicked
        if (principal.ejecutarHistorial()) {
            this.dispose();
        }
    }//GEN-LAST:event_lblHistorialMouseClicked

    private void lblHistorialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistorialMouseEntered
        lblHistorial.setForeground(Color.red);
        lblHistorial.setToolTipText("Muestra el historial de entradas y salidas");
    }//GEN-LAST:event_lblHistorialMouseEntered

    private void lblHistorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHistorialMouseExited
        lblHistorial.setForeground(Color.black);
    }//GEN-LAST:event_lblHistorialMouseExited

    private void lblModificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificacionMouseClicked
        try {
            dialogModificacione.setVisible(true);
            dialogModificacione.setLocationRelativeTo(null);
            dialogModificacione.setSize(280, 241);
            dialogModificacione.setUndecorated(true);
        } catch (IllegalComponentStateException e) {
            
        }
    }//GEN-LAST:event_lblModificacionMouseClicked

    private void lblModificacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificacionMouseEntered
        lblModificacion.setForeground(Color.blue);
    }//GEN-LAST:event_lblModificacionMouseEntered

    private void lblModificacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificacionMouseExited
        lblModificacion.setForeground(Color.black);
    }//GEN-LAST:event_lblModificacionMouseExited

    private void lblNuevoMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevoMaterialMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNuevoMaterialMouseClicked

    private void lblNuevoMaterialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevoMaterialMouseEntered
        lblNuevoMaterial.setForeground(Color.red);
    }//GEN-LAST:event_lblNuevoMaterialMouseEntered

    private void lblNuevoMaterialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevoMaterialMouseExited
        lblNuevoMaterial.setForeground(Color.black);
    }//GEN-LAST:event_lblNuevoMaterialMouseExited

    private void lblNuevoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevoUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNuevoUsuarioMouseClicked

    private void lblNuevoUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevoUsuarioMouseEntered
        lblNuevoUsuario.setForeground(Color.red);
    }//GEN-LAST:event_lblNuevoUsuarioMouseEntered

    private void lblNuevoUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevoUsuarioMouseExited
        lblNuevoUsuario.setForeground(Color.black);
    }//GEN-LAST:event_lblNuevoUsuarioMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCerrarSesion;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JDialog dialogModificacione;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblEntradaMaterial;
    private javax.swing.JLabel lblHistorial;
    private javax.swing.JLabel lblModificacion;
    private javax.swing.JLabel lblNuevoMaterial;
    private javax.swing.JLabel lblNuevoUsuario;
    private javax.swing.JLabel lblSalidaMaterial;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
